title:
description: >
baseurl: "" # the subpath of your site, e.g. /blog
url: "pedroelayla.com" # the base hostname & protocol for your site, e.g. http://example.com

include: ["_pages"]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
